### ISSUE TITLE
Open Opensubtitle page using the same language configured in uploader.

### ISSUE THREAD

**Issue by Bricio** [vankasteelj/opensubtitles-uploader#101]
Uploader app is configured with english language.
But the link generated after you upload the subtitle links is hardcoded to french location of the site.

It should be coded using localStorage.locale variable, or something like that.

![image](https://user-images.githubusercontent.com/216170/173595583-7cf9940f-c74c-4aca-978b-23fd616c98a8.png)

![image](https://user-images.githubusercontent.com/216170/173595670-491d8bb3-654b-450e-a7e3-0ce31154bebb.png)

https://github.com/vankasteelj/opensubtitles-uploader/blob/5becbb75e503588cd61d15e18200cc92752bb34e/app/js/main/osactions.js#L371-L372

**Comment by vankasteelj** [comment]
It is a known issue, I haven't looked into it yet. Related to https://github.com/vankasteelj/opensubtitles-uploader/pull/98
