### ISSUE TITLE
No Media Info

### ISSUE THREAD

**Issue by uckthis** [vankasteelj/opensubtitles-uploader#103]
For some time now, the media info section of the software is always empty. If I accidentally upload a subtitle, mods deactivate it because it doesn't mention the frame rate. I did try to replace the ffmpeg.dll with older versions and the app stopped working. Any ideas?

![InkedUntitled_LI](https://user-images.githubusercontent.com/28671050/190894950-7c59dc30-c98a-47a3-a414-0a18d0a063fe.jpg)

**Comment by fun7om** [comment]
Please look here. https://github.com/vankasteelj/opensubtitles-uploader/issues/94
there is workaround

**Comment by uckthis** [comment]
Thank you, worked.
