### ISSUE TITLE
Profile can not be used

### ISSUE THREAD

**Issue by doglover3920** [vankasteelj/opensubtitles-uploader#104]
During start-up, I get the message that my profile cannot be used, because it is made with a newer version of something.
The app starts up and this message disappears.

But for as far as I can see, the app works normal.

**Comment by vankasteelj** [comment]
Sounds like a nwjs issue, you might want to clear `%appdata%\opensubtitles-uploader` on Windows. See https://github.com/nwjs/nw.js/issues/6188

**Comment by doglover3920** [comment]
Thanks.  Seemed to work.
