### ISSUE TITLE
Trying to build 2.7.0 on Linux (Arch)

### ISSUE THREAD

**Issue by tyhawk** [vankasteelj/opensubtitles-uploader#106]
I'm trying to build version 2.7.0 on (Arch) Linux, but running into issues. I'm not a developer, so I may be asking something obvious to a developer. If so, my apologies.

After ` gulp build`  I get:
```
Error: Cannot find module 'nw-builder/lib/detectCurrentPlatform.js'
Require stack:
- /home/USER/Development/PKGBUILD/opensubtitles-uploader/src/opensubtitles-uploader-2.7.0/gulpfile.js
- /usr/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js
- /usr/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /usr/lib/node_modules/gulp/node_modules/gulp-cli/index.js
- /usr/lib/node_modules/gulp/bin/gulp.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/home/USER/Development/PKGBUILD/opensubtitles-uploader/src/opensubtitles-uploader-2.7.0/gulpfile.js:20:23)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/USER/Development/PKGBUILD/opensubtitles-uploader/src/opensubtitles-uploader-2.7.0/gulpfile.js',
    '/usr/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/usr/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/usr/lib/node_modules/gulp/node_modules/gulp-cli/index.js',
    '/usr/lib/node_modules/gulp/bin/gulp.js'
  ]
}
```
The module is packages with the tar.gz, but is in a different place:
```
src/opensubtitles-uploader-2.7.0/node_modules/nw-builder/src/utilities/detectCurrentPlatform.js
```
I am unsure how to fix this or what is going wrong.

NPM version 8.19.2
Gulp version 4.0.2

**Comment by vankasteelj** [comment]
Mh, you could try to change `nw-builder/lib/detectCurrentPlatform.js` to `nw-builder/src/utilities/detectCurrentPlatform.js` in the gulp.js file, line 20, which is currently :

 `    currentPlatform = require('nw-builder/lib/detectCurrentPlatform.js'),`

**Comment by tyhawk** [comment]
@vankasteelj Followed your advice and this is the next hump:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/USER/Downloads/opensubtitles-uploader-2.7.0/node_modules/nw-builder/src/utilities/detectCurrentPlatform.js from /home/USER/Downloads/opensubtitles-uploader-2.7.0/gulpfile.js not supported.
Instead change the require of detectCurrentPlatform.js in /home/USER/Downloads/opensubtitles-uploader-2.7.0/gulpfile.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/USER/Downloads/opensubtitles-uploader-2.7.0/gulpfile.js:20:23) {
  code: 'ERR_REQUIRE_ESM'
}
```
(I'm starting to get it to build manually now before I continue working on my PKGBUILD, so the directory-structure is slightly different from my previous post).

**Comment by vankasteelj** [comment]
Oh okay, I see what's wrong. You're not using the correct version of nwbuilder.

**Comment by vankasteelj** [comment]
You should change in package.json the line "nwbuilder"

Currently it is: 
```"nw-builder": "^3.5.7",```
and it should be: 
```"nw-builder": "3.6.0",```

Then doing a `npm install` again should fix it. I believe the person who took over the nw-builder code did some wierd things with it, maybe they didn't follow semver and pushed a breaking change with a new version.

**Comment by tyhawk** [comment]
Thanks! I managed to build it for Linux now. As I always have plenty of Linux machines (I've been a Linux system administrator for the past 25 years), I'd be happy to help you build binaries for Linux for this project, so you can provide the Linux community with the binaries again.

I'll work with the maintainer of the AUR package (https://aur.archlinux.org/packages/opensubtitles-uploader) so that gets updated to the current version.
