### ISSUE TITLE
"unknown Opensubtitles related error, please retry later or report the issue"

### ISSUE THREAD

**Issue by pipporan** [vankasteelj/opensubtitles-uploader#107]
hello
i've uploaded thousands of subs with opensutitlesuploader during the years (by the way, congratulations, it's a very fine piece of software!), and i dont remember it has ever shown this error. When i drag a video file into the window (or i browse for a file, it's the same), in the same time - about one second - it usualy hashes the file and extract all the informations, it just appears this little label on the up-right corner of the window, saying "unknown Opensubtitles related error, please retry later or report the issue", and nothing else happens: the video file is not charged, so there is nothing to do. It happens to be a problem of mine only, because i've seen users uploading subs with it at the very same time (and after) my software didnt work (instead, yesterday and the past days it worked like a charm). I just tried deleting and recopying the files (i'm using and i've always used the portable version, 2.7.0, for Windows 64bit), i tried to logout, then to login again, and nothing changed.
![opensubs uploader error](https://github.com/vankasteelj/opensubtitles-uploader/assets/80214830/750f4100-092e-492a-ad2c-498e3f236504)
 I have no more idea about what to try next.
Any heads-up?
Bye

**Comment by pipporan** [comment]
two additional things:
i just tried installing the setup version...and it works!!!

and, just as additional info i forgot earlier, there is an error message that shows up as the program is loading (before the main window shows up), i leave the image here (it's in italian, even if i changed the language of the uploader to english. I didnt associate this error with the video files not being loaded just because it's a couple of months this error shows up, and it never prevented the software from working.
It says:
"Error with the profile
Impossible to use your profile because it comes from a more updated version of NW.js.
Some functions may not be available. Specify another directory for the profile or use a more recent version of NW.js."
I dont know what it is...java stuff? (im really not educated to software engineering, java codes, pythoon, and so on:-)
![opensubs uploader error_2](https://github.com/vankasteelj/opensubtitles-uploader/assets/80214830/06216c03-53f3-4fc9-8d00-70b506160b53)

**Comment by vankasteelj** [comment]
For the profile issue you might want to delete `%localappdata%\nwjs` and `%localappdata%\opensubtitles-uploader`

**Comment by vankasteelj** [comment]
for the "unkown" error message, I cannot reproduce even with the portable version. When the error occurs, please press CTRL+D or F12 while using the app, a "devtool" will open. Navigate to the "console" or "terminal" tab, and see if there is an error. I've tried to keep the logs human-understandable, so you should identify an error code or message, copy/paste it here or upload a screenshot.

**Comment by pipporan** [comment]
first, let me the (first, maybe?) to give you a big thanks and congrats for version 2.8.0!!!!!!

i already tried it: greek is still the black sheep:-), but quite big improvements on CZE,TUR,SLO (SLV was fine already in old versions), SPA (seems to catch it most times, before it was random!)

MAY (Malay) still gets confused with indonesian, NOR still struggles most times, greek is a black hole, chineses are all the same, and portugueze (of course) are all the same

great, basically half of the problematic languages are much better recognized!

and the "search directly on IMDB" now seems to work!

 

Versions 2.8 seems to have solved my problem too: all the videos are being hashed regularly...

 

About my issue with 2.7.0 (i tried 2.6 too: same errors than 2.7): deleting the files in "appdata/local" folder worked for the NWjs error (even if i didnt have a "NWxx" directory, just the "opensubtitles-uploader")

The NWjs error disappear, but instead, as soon as i started the dev-tools, ALL versions began to not work (apart from 2.8, it still works)...2.7 and 2.6, both installed and portable, began immediately gave the hash error...

 

this is the console:

 

app.js:4 Opening app...
boot.js:157 Portable application, loading settings from `osu.json` Object
localization.js:47 Using locale: en
interface.js:210 Logged in! (as pipporan - ID:7541493)
app.js:40 Application ready: 285.791259765625 ms
files.js:29 Detecting quality...
interface.js:41 Adding new video!
interface.js:182 Error: 401 Unauthorized
at d:\Programmi\opensubtitles-uploader-2.7.0-win32-portable\node_modules\opensubtitles-api\index.js:58:19
at processTicksAndRejections (node:internal/process/task_queues:96:5)
(anonymous) @ interface.js:182
keyboard.js:19 Opening devtools

 

i attach the screenshot, you understand it better

**Comment by pipporan** [comment]
![opensubs devtolols](https://github.com/vankasteelj/opensubtitles-uploader/assets/80214830/54213235-913a-4476-b7e1-0ca4839d5d54)

**Comment by tbertels** [comment]
I've had that error shown on some videos/subtitles for quite some time, with no visible problem.

Here's the error message for the latest uploaded one:

> files.js:29 Detecting quality...
interface.js:41 Adding new video!
files.js:183 MediaInfo data: {file: 'D:/-- Download/[something].mkv', general: {…}, video: Array(1), audio: Array(1), text: Array(1)}
interface.js:137 Matching subtitle detected
osactions.js:326 Unknown OpenSubtitles related error, please retry later or report the issue
(anonymous) @ osactions.js:326
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.catch (async)
imdbMetadata @ osactions.js:325
(anonymous) @ interface.js:111
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
(anonymous) @ interface.js:106
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
add_video @ interface.js:56
handleDrop @ dragdrop.js:45
window.ondrop @ dragdrop.js:114

If I retry with a dummy 1 second video file and the same subtitle I get the same error.
I get the same error too with a dummy 1 second video file and a subtitle that doesn't normally show an error.
So in my case, this seems related to the video file.

I tried checking the HTTP response from the server, but it's not shown. It may be useful to show it in the error message.

**Comment by tbertels** [comment]
I've just had a different variation of that error (reproducible with the same video file):

> app.js:4 Opening app...
localization.js:47 Using locale: en
interface.js:210 Logged in! (as [user] - ID:12345)
app.js:44 Application ready: 553.635986328125 ms
files.js:29 Detecting quality...
interface.js:41 Adding new video!
interface.js:182 TypeError: Cannot read properties of undefined (reading 'length')
    at C:\Program Files\OpenSubtitles Uploader\node_modules\opensubtitles-api\index.js:190:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(anonymous) @ interface.js:182
keyboard.js:19 Opening devtools
files.js:29 Detecting quality...
interface.js:41 Adding new video!
interface.js:182 TypeError: Cannot read properties of undefined (reading 'length')
    at C:\Program Files\OpenSubtitles Uploader\node_modules\opensubtitles-api\index.js:190:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(anonymous) @ interface.js:182
keyboard.js:19 Opening devtools

**Comment by vankasteelj** [comment]
You'll have to give me the errors on the last version (2.8.0). I cannot support 2.7.x or 2.6.x as that is "old code". 

Also you can "expand" the error by clicking the small ">" symbol on the error message, to display the complete error stack. 

Final note: if the error is an HTTP code, then the issue is with Opensubtitles, not me.

**Comment by pipporan** [comment]
If only 2.8.0 errors are useful to you, so we can close it here, 'cos fortunately with 2.8.0 version this issue disappeared (and hope it will stay away).

**Comment by tbertels** [comment]
The errors I've reported are on 2.8.0

**Comment by vankasteelj** [comment]
I cannot reproduce the issue. Can you give the expanded error? By clicking on the little "arrow" `>` on the error message. It should show you several lines in red, instead of just one

**Comment by pipporan** [comment]
i think he was replying to you: he cant use error codes from version older than 2.8, and i don't have errors from version 2.8...so, there's no compatibility:-)

**Comment by tbertels** [comment]
Since I exported the full errors to a file, it doesn't make sense either if he's replying to me. 😕

**Comment by pipporan** [comment]
oh....ok

**Comment by mellowgeekcc** [comment]
I am having the same issue with version 2.8.0. It happens only with a determined video file. It seems to be related to its length. Here is the log:

`Detecting quality... files.js:29 
Adding new video! interface.js:41 
TypeError: Cannot read properties of undefined (reading 'length') interface.js:182 
    at C:\Program Files\OpenSubtitles Uploader\node_modules\opensubtitles-api\index.js:190:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(anonymous)	@	interface.js:182
processTicksAndRejections	@	node:internal/process/task_queues:95
Promise.catch (async)		
add_video	@	interface.js:162
handleDrop	@	dragdrop.js:45
window.ondrop	@	dragdrop.js:114`

**Comment by vankasteelj** [comment]
The error says there is missing information in the response from opensubtitles servers, or no response at all (https://github.com/vankasteelj/opensubtitles-api/blob/master/index.js#L190C32-L190C32). I cannot debug this, it's related to opensubtitles, not my app.

**Comment by tbertels** [comment]
@vankasteelj What about https://github.com/vankasteelj/opensubtitles-uploader/issues/107#issuecomment-1544052550?

**Comment by vankasteelj** [comment]
It's the same: an error on opensubtitles side. Their servers are not giving back correct information. There is nothing I can do about it, it's their "CheckMovie" api call that doesn't seem to answer an expected response for those files.
