### ISSUE TITLE
Error: "Cannot read properties of undefined (reading 'trim')"

### ISSUE THREAD

**Issue by melissis** [vankasteelj/opensubtitles-uploader#109]
The program works fine for me, including adding video files with upload, except for a particular video file when I try to load it. The UI gives this error:
`Unknown OpenSubtitles related error, please retry later or report the problem.`
I have tried later. It still works with other video files.
The console gives this error:
```Cannot read properties of undefined (reading 'trim')
    at LibID.parseResponse (C:\Program Files\OpenSubtitles Uploader\node_modules\opensubtitles-api\lib\identify.js:44:80)
    at C:\Program Files\OpenSubtitles Uploader\node_modules\opensubtitles-api\index.js:201:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(anonymous) @ interface.js:182
    processTicksAndRejections @ node:internal/process/task_queues:95
    Promise.catch (async)
    add_video @ interface.js:162
    handleDrop @ dragdrop.js:45
    window.ondrop @ dragdrop.js:114
```
And none of the video fields gets filled in. Uploading only the srt worked, but I would like to upload the hash as well.

This is version 2.8.0.

**Comment by vankasteelj** [comment]
Have you retried after a few hours? Or tried another video file around the same time? It most brobably is Opensubtitles servers being grumpy for some reason, seeing the error message and code.

**Comment by melissis** [comment]
> Have you retried after a few hours? Or tried another video file around the same time? It most probably is Opensubtitles servers being grumpy for some reason, seeing the error message and code.

I did both of those, yes. Works with other files.
And the video file won't even load in the software, so wouldn't that indicate an issue with the software?

**Comment by vankasteelj** [comment]
No, because the error comes from the opensubtitles API, otherwise it wouldnt be "unknown opensubtitles error". Can you send me a WeTransfer with the video file in question? So I can see for myself

**Comment by melissis** [comment]
> Can you send me a WeTransfer with the video file in question? So I can see for myself

I send you an email.

**Comment by vankasteelj** [comment]
Got it
