### ISSUE TITLE
opensubtitles-uploader-2.8.0-win32-setup.exe entry point SetProcessMitigationPolicy not found in KERNEL32.dll

### ISSUE THREAD

**Issue by cleaningdust** [vankasteelj/opensubtitles-uploader#112]
Hi :

Error at launch / start. Same resulat as start with administrators rights.
Setup : opensubtitles-uploader-2.8.0-win32-setup.exe
Error : entry point SetProcessMitigationPolicy not found in KERNEL32.dll
OS : Windows 7 Ultimate 64 bits FRE Version 7061 SP1

Regards.

![opensbubtitles entry point fail](https://github.com/vankasteelj/opensubtitles-uploader/assets/72855648/0bea4d90-7650-4d60-b983-2402453530df)

**Comment by vankasteelj** [comment]
Windows 7 is dead sine january 2020, might that be it? Can you reproduce with an up-to-date version of Windows?
