### ISSUE TITLE
uploads itself marked as "subtitle hearing impaired".

### ISSUE THREAD

**Issue by kokolakiss** [vankasteelj/opensubtitles-uploader#115]
I am very happy with OpenSubtitles Uploader version 2.80.

I would like to ask you, although the subtitle file is not for the hearing impaired, sometimes it uploads itself marked as "subtitle hearing impaired".

Thank you in advance for all your attention.

**Comment by vankasteelj** [comment]
Hi, you'll have to provide some examples. The uploader marks files as "hearing impaired" if there are too many parenthesis in the subtitle file, as they usually are only used massively on HI subtitles. It does, though, only "check" the checkmark and not automatically uploads something you are not OK with. So maybe check if the subtitles you drop in the app and that you upload mark themselves as Hearing Impaired and uncheck the "HI" mark.
