### ISSUE TITLE
Something is not working correctly

### ISSUE THREAD

**Issue by Maxoudela** [vankasteelj/opensubtitles-uploader#17]
I try to upload a subtitle for a movie but I get the message "Quelque chose a mal fonctionné :("

Where can I go to get a stackTrace of the error? I can provide the file and the subtitle if you want to reproduce.

**Comment by vankasteelj** [comment]
if you open devtools (ctrl+d) you should should see the error in details. the error you describe is most probably on OpenSubtitles end, a request not sending back 200 (success), nor 503 (temporarily unavailable) nor 506 (maintainance), but something else.

**Comment by Maxoudela** [comment]
I have a "402 subtitles has invalid format (B)"
My srt file is named "Mr.Robot.109.WEB-DL.FR.NoTAG"

**Comment by vankasteelj** [comment]
can you upload your sub here? (drag&drop in a zip) your sub is most probably broken

**Comment by Maxoudela** [comment]
[Mr.Robot.109.WEB-DL.FR.NoTAG.zip](https://github.com/vankasteelj/opensubtitles-uploader/files/238775/Mr.Robot.109.WEB-DL.FR.NoTAG.zip)

**Comment by vankasteelj** [comment]
encoding, timecodes and lines seem fine though. Did you retry to upload?

**Comment by vankasteelj** [comment]
ah, I see 307 and 308 are overlapping each other (00:21:08,522 twice)

**Comment by Maxoudela** [comment]
Yes right, I'll correct that and try to upload it again. If it's not working, it will mean that others are overlapping too..

**Comment by vankasteelj** [comment]
it's the only one overlap. You should use SubtitleEdit, it's a great tool on windows. There's gaupol on linux, but it's not as good.

**Comment by Maxoudela** [comment]
[Mr.Robot.109.WEB-DL.FR.NoTAG (2).zip](https://github.com/vankasteelj/opensubtitles-uploader/files/238808/Mr.Robot.109.WEB-DL.FR.NoTAG.2.zip)

I modified it so it's not overlapping but I still get the same error :/

**Comment by vankasteelj** [comment]
the issue def is with OpenSubtitles, I think. I'm trying various things

**Comment by vankasteelj** [comment]
I found the error, it's the advertisement for u-sub.net and sous-titres.eu on line 22. They speak about that in the forum.

**Comment by Maxoudela** [comment]
Huum Allright, I'll try by removing them

**Comment by vankasteelj** [comment]
https://github.com/vankasteelj/opensubtitles-uploader/commit/cf1b847d3c2e967f7a2cb6d92d498a1b1f2ac536 and https://github.com/vankasteelj/opensubtitles-uploader/commit/65e504989a3d1952260ec9c7463ae5eeb86802cd
