### ISSUE TITLE
Uploader doesn't accept subtitles from opensubtitles.org

### ISSUE THREAD

**Issue by l0co** [vankasteelj/opensubtitles-uploader#33]
From time to time I adjust subtitles from opensubtitles.org to the video file I have. Then I usually upload it to opensubtitles. The file uploaded is the original subtitles file, but adjusted to concrete video using Gaupol transform function.

I tried your application but it refuses to upload such file, claiming that is "has wrong format and may contain competitive URL-s" - my free translation of polish UI message :) 

The subtitles file and the screen are attached.
[Game.of.Thrones.S06E08.720p.WEBRiP.x264-BestKorea.pl.srt.gz](https://github.com/vankasteelj/opensubtitles-uploader/files/312595/Game.of.Thrones.S06E08.720p.WEBRiP.x264-BestKorea.pl.srt.gz)
![zrzut_ekranu-opensubtitles uploader](https://cloud.githubusercontent.com/assets/1880196/16021047/e831745c-31b0-11e6-8672-89177069bcad.png)

**Comment by vankasteelj** [comment]
You need to see with OpenSubtitles, I have nothing to do with which subtitles they accept or don't

**Comment by l0co** [comment]
Sure.

I'm not so desperate with uploading these subtitles to look for the solution and to report this problem in different places. I was just sharing transformed subtitles as a "quid pro quo". If it's not possible anymore I just won't be doing this ;)
