### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by Transcodes** [vankasteelj/opensubtitles-uploader#35]
error on 64 bit windows 10 when trying to login
worked fine till 2 days ago on 32-bit Windows 10

**Comment by vankasteelj** [comment]
I cannot reproduce

**Comment by devcompl** [comment]
It works now, I had the same problem.

What was happening is that every time I tried to drag/drop a video file, the "There was a problem with OpenSubtitles, please try again later" or something like that error was showing.
Tried to relog, but when I tried to login again it was showing "certificate has expired" error like OP says.

Maybe that will help.

**Comment by vankasteelj** [comment]
it's a problem with opensubtitles then, because I don't use certificates and this error only shows up when os servers don't respond. There's nothing I can do about it :/
