### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by opensubtitles** [vankasteelj/opensubtitles-uploader#39]
Hi

opensubtitles.org is using to https, now uploader is reporting UNABLE_TO_VERIFY_LEAF_SIGNATURE, unable to verify the first certificate

when uploading subtitles.

Please look at it, thanks

**Comment by vankasteelj** [comment]
I can't reproduce it. Are you using 2.1.0? Because I just uploaded a subtitle without trouble (apart from an occurence of xmlrpc invalid tag "TITLE" when verifying the imdbid, that happens from time to time using your API, but that's not new)

**Comment by vankasteelj** [comment]
The issue doesn't come from the browser but from a mismatch between the user's certificates and the ones presented by OpenSubtitles. I would suggest to update the operating system and maybe double-check OpenSubtitles' certificates. There are workarounds for this, but it's unsecure for the user to send a password over non-ssl connections. I will add an option to use HTTP, but won't activate it by default.

**Comment by opensubtitles** [comment]
ok, so we find out there was problem with hosts file (fixing VLSub). It happens to me. Now certificate is valid only for opensubtitles.org served by CloudFlare. If somebody have direct access (edited hosts file) to our servers, he will get wrong certificate, so all is good.
