### ISSUE TITLE
Loading gear keeps spinning after loading video

### ISSUE THREAD

**Issue by sharkile** [vankasteelj/opensubtitles-uploader#40]
When a video is loaded into the app the loading gear keeps spinning even after successfully uploading the subtitle, another video and sub can be loaded afterwards but the gear remains there.
Log file is attached.

![screenshot from 2017-04-25 12-49-31](https://cloud.githubusercontent.com/assets/17736615/25416001/a6222f20-29f8-11e7-8474-12ba96ef501f.png)

[log.txt](https://github.com/vankasteelj/opensubtitles-uploader/files/957079/log.txt)

**Comment by vankasteelj** [comment]
Ok thanks, i'll attach cleaform to hiding the spinner
