### ISSUE TITLE
FPS field; erasing fields on network failure

### ISSUE THREAD

**Issue by alexpavlovic** [vankasteelj/opensubtitles-uploader#41]
Dear sir,

There are 2 issues I have encountered so far:
1. In case of subtitle upload only, without any video file, FPS field does not receive value, but does not allow for manual input of frame rate either. Therefore, uploaded subtitles lack that info.
2. In case the site 'opensubtitles.org' is unreachable for any reason, dialog pops-up with 'Retry'/'OK' buttons. 'Retry' just retries and sooner or later one has to press 'OK'. After pressing OK all data in the window are deleted! A sort of save option would be nice instead.

Wish you many good prog-lines :)
Alex

**Comment by vankasteelj** [comment]
Locking the FPS info was asked by the opensubtitles admin, because it's a sensitive case. I could make an "advanced" option to allow modifying manually all fields, but they have to stay locked by default.

I'll think about the 2nd issue, thanks

**Comment by alexpavlovic** [comment]
In general, there are 3 cases of upload:
1. video only,
2. video and subtitle, and
3. subtitle only.
I guess that your program works well with first two options, and in line
with sysadmins' requests, but in third option it failes to collect FPS. I
don't know if it is possible at all to get FPS via some auto mode while in
case 3? If not, then sysadmins should rethink their requests. On one side
there are obligations of translators to fill all the data about the video
and subtitle, which is reasonable and correct, on the other we cannot do
that in one pass, using your program due to incompatible limitations, and
need to connect to 'opensubtitles.org' site to make correction report for
each uploaded subtitle considering FPS field. This situation is
contradictory to general demand of programming itself, to make our life and
work easier not harder. I hope that you will resolve with them this
situation and make us happy with new version of your program. Thank you for
your answer and keep up the good work, :)
Alexander Pavlovic

**Comment by vankasteelj** [comment]
the FPS is "frame per second", how do you expect a .txt of having a number of frames? It's only video files

**Comment by alexpavlovic** [comment]
No, not the subtitle file. But, when uploading subtitle it is necessary to
have a video file release name which corresponds to the subtitle. With that
name maybe it is possible to initiate the search on 'opensubtitles.org'
servers to find needed video file and get FPS information from it. I was
wandering, in previous letter, if this scenario is viable in general.

**Comment by vankasteelj** [comment]
It's not necessary to have a video file release name. You can just drop your subtitle and hit upload
