### ISSUE TITLE
When starting 2.2.0, incl. Portable: Entry point in ReleaseSRWLockExclusive not in KERNEL32.dll.

### ISSUE THREAD

**Issue by Masutin** [vankasteelj/opensubtitles-uploader#43]

**Comment by vankasteelj** [comment]
You might need to install Visual C++ 2008 SP1 Redistributable Package (x86), or you're on Windows XP which has no support from NWJS (and I can't help you).

**Comment by MMasutin** [comment]
Was there a version that supports Windows XP?
