### ISSUE TITLE
How does the Auto detect the Language work

### ISSUE THREAD

**Issue by Rouzax** [vankasteelj/opensubtitles-uploader#47]
When I add a video file and subtitles the Auto detect the Language never works.
My files are called:
```
Lethal Weapon - S01E01 - Pilot (1080p.BluRay.rovers).en.srt
Lethal Weapon - S01E01 - Pilot (1080p.BluRay.rovers).mkv
```

**Comment by Rouzax** [comment]
When I add a video file and subtitles the Auto detect the Language never works.
My files are called:
```
Lethal Weapon - S01E01 - Pilot (1080p.BluRay.rovers).en.srt
Lethal Weapon - S01E01 - Pilot (1080p.BluRay.rovers).mkv
```

**Comment by svaraej** [comment]
It uses npm detect-lang. Therefore it (if I understand it correctly) checks the content of the sub and not the filename.

Links to lines in the code with comments about the language detection feature:
https://github.com/vankasteelj/opensubtitles-uploader/blob/493fcaf0be89d093120e868e433b524fcb33510e/app/js/main/files.js#L60
https://github.com/vankasteelj/opensubtitles-uploader/blob/493fcaf0be89d093120e868e433b524fcb33510e/app/js/main/files.js#L76
