### ISSUE TITLE
Uploading ass subtitles

### ISSUE THREAD

**Issue by NunoVilhenaSantos** [vankasteelj/opensubtitles-uploader#48]
Hi,
I'm constantly having troubles uploading some ass subtitles, and i thing it's because they are above 100 kb.

Specially the anime's ass are to elaborate and there for even on a 20 something minutes of a episode the get very large files (i don't think they are that large but!).

What can i do so we can solve some of this problems?
Where can a sent those files for your to be able to see what the problem and what should be done the resolve them?

Thanks in advanced.

Nuno

![2018-03-13 05-44-55 opensubtitles uploader](https://user-images.githubusercontent.com/9029791/37324520-baf48692-2681-11e8-94c5-4b8ca64eb4a8.png)

**Comment by vankasteelj** [comment]
Have you tried uploading them directly to the website? Does it work? That error message is an error sent back by the OSS server, I think

**Comment by vankasteelj** [comment]
Closing until further info is given
