### ISSUE TITLE
[INFO] IMDB api might be offline

### ISSUE THREAD

**Issue by opensubtitles** [vankasteelj/opensubtitles-uploader#49]
Hi,

I saw for latest bugfix: "bug fix: the IMDB api might be offline, you can still set manually an id" - which XML-RPC API methods doesnt work for you ? Please send examples method name and parameters, so I can check what is wrong.

thanks

**Comment by MartyTurbo2** [comment]
Hi there, the website seems to be down. Is it under maintenance?

**Comment by vankasteelj** [comment]
Call:
`OS.api.GetIMDBMovieDetails(<VALID OS TOKEN>, '0365748').then(console.log).catch(console.error)`

XML call: 
`struct GetIMDBMovieDetails(string $token, string $imdbid)`

Response (error message): 
"API seems offline"

**Comment by opensubtitles** [comment]
hi, should be fixed. sometimes needs to be reloaded, if returns empty results (it was broken before, but it is fixed now and empty values are cached...). Anyway, I think from your side nothing needs to be changed.

**Comment by vankasteelj** [comment]
Yes, these are 2 of the few errors I encountered using your API over the years, so I try to catch them to display an actual message to the user: 

https://github.com/vankasteelj/opensubtitles-uploader/blob/144051d7321633711a6256ec6916066afbb3a67e/app/js/main/osactions.js#L252

**Comment by david1542** [comment]
Hi guys! I'm also getting an error 'API seems offline' whenever I try to search for subtitles in your api.
Could you check it please?

**Comment by vankasteelj** [comment]
I'm closing this as it is not related to the opensubtitles-uploader per say. Maybe move the discussion to the forum of opensubtitles
