### ISSUE TITLE
Weird characters for greek subs

### ISSUE THREAD

**Issue by FRENCHROLLINGSTONER** [vankasteelj/opensubtitles-uploader#50]
I have a problem. I try to upload Greek subs for a movie but the OpenSubs uploader "read" them as Arabic. 
And on the opensubs.com site appear with weird characters. Why is that? Please help me.

**Comment by vankasteelj** [comment]
A few questions: 

1) "OpenSubs uploader "read" them as Arabic": you mean with the autodetect language?

2) Have you tried to manually select "greek" in the dropdown menu? If so, does opensubtitles displays the sub correctly?

**Comment by vankasteelj** [comment]
closing until further information
