### ISSUE TITLE
Video file is not available online after using Opensubtitles uploader (???)

### ISSUE THREAD

**Issue by AdrianMartan** [vankasteelj/opensubtitles-uploader#51]
Hi,
In normal case the Opensubtitles uploader work just fine.
But sometimes during the same upload proces there are some video files i just can't upload.
It says: "We already have this video file in database. The hash too... The movie file too..."
So this video file isn't available online by using program like BS player. But the same video file is available
for other subtitles, just my subtitle isn't among the other subtitles for this video file.
Here's the name of the video file: [TorrentCounter.to].Avengers.Infinity.War.2018.New.HD-TS.x264
And here's the link to my subtitle that suits the video file:
https://www.opensubtitles.org/en/subtitles/7357088/avengers-infinity-war-hr
I have tried like 20 times to upload the video file using Opensubtitles uploader version 2.3.0, and version
2.2.0 and 2.1.0 but nothing no result. I contact administration, they say it takes time for upload and i
should be patient. But it takes like 6 to 10 hours at most for the video file to be uploaded, often even immediately.
Someone please help.
Adrian aka Neeboo

**Comment by vankasteelj** [comment]
I sadly cannot help you, you should check on Opensubtitles directly, and see with them. I do not manage the database, I merely interact with it.
