### ISSUE TITLE
"Release name" field is always takes the defualt name

### ISSUE THREAD

**Issue by fun7om** [vankasteelj/opensubtitles-uploader#52]
doesnt matter what i type at "Release name" field,
always stays the same as the file name.
or im doing somthing wrong?

**Comment by bonebizz21** [comment]
> doesnt matter what i type at "Release name" field,
> always stays the same as the file name.
> or I'm doing something wrong?

**Comment by bonebizz21** [comment]
Doesn't

**Comment by vankasteelj** [comment]
I'll have to check that

**Comment by fun7om** [comment]
> Doesn't

Well, thank you for correcting me.

So vankasteelj, im still here if you need additional info.

**Comment by vankasteelj** [comment]
You seem to do something wrong, it works fine for me. Uploading a subtitles, with a custom "release name", does make the "release name" that custom string of text on opensubtitles' website.

**Comment by fun7om** [comment]
hey vankasteelj. it seems im not only one havin this issue.
this is explaind by SmallBrother at OpenSubtitles forum
https://forum.opensubtitles.org/viewtopic.php?f=11&t=15404&start=135#p40879

thank you for your help.

> - Take the uploader of vankasteelj
> - Make a subtitle file which is called (for example) Nice_Movie (2010) dut.srt
> - Load this into the uploader
> - Check IMDB ID so that it is matching (in this example fictional movie name) Nice Movie of 2010
> - Write as release name OCR DVD-rip
> - Upload
> 
> Now the subtitle appears with release name Nice_Movie (2010) dut (i.e. the same as subtitle file name minus the extension SRT)
> But it SHOULD have been OCR DVD-rip
