### ISSUE TITLE
opensubtitles-uploader does not upload video and subtitle files

### ISSUE THREAD

**Issue by tracyvanlone** [vankasteelj/opensubtitles-uploader#53]
I uploaded the video file, then the subtitle file. When I hit the "upload" button, I got an error ("something went wrong :(" ) and was asked if I would like to try again. I clicked "yes" but I still go the error message. My video was a 22-minute .mp4 file and my subtitles were a .srt file.

**Comment by vankasteelj** [comment]
closing as there is no more response
