### ISSUE TITLE
Switch To Online Uploader

### ISSUE THREAD

**Issue by phistuck** [vankasteelj/opensubtitles-uploader#54]
I see that MediaInfo has managed to create a version that operates entirely within a browser (it does not upload the file to the server or anything like that) -
https://mediaarea.net/MediaInfoOnline

So perhaps there is no need for a downloadable/installed uploader anymore and you can just create a normal web page that does the same thing?

**Comment by vankasteelj** [comment]
mmmh, maybe. I don't really do well with web browsers, there is no nodejs

**Comment by phistuck** [comment]
The Node.js API is not there, clearly, but it is still JavaScript and most of the modules are, well, JavaScript that you can simply use in web browsers.

**Comment by vankasteelj** [comment]
I don't have the time nor the knowledge to perform that kind of interaction with opensubtitles without using node. I'm sorry, but you should maybe check with OpenSubtitles directly, maybe there someone can improve the current online uploader.
