### ISSUE TITLE
Add support for IETF language codes detection

### ISSUE THREAD

**Issue by duramato** [vankasteelj/opensubtitles-uploader#56]
This is a simple request to add detection of [IETF language codes](https://en.wikipedia.org/wiki/IETF_language_tag).
Currently when a pt-BR subtitle ie `The.Office.S02E15.Boys.and.Girls.1080p.WEB-DL.x264-TrollHD.pt-BR.srt` gets selected it detects as Portuguese, which isn't correct as the IETF code for Portuguese is `pt`. which as well it's [2 letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) so it wouldn't break any current behaviour

This would also be usefull for Chinese (Traditional) and Chinese simplified which are represented with `zh-CN` and `zh-TW` respectively

More info: 
https://en.wikipedia.org/wiki/IETF_language_tag
https://gist.github.com/traysr/2001377#commonly-used-ietf-language-tags

**Comment by vankasteelj** [comment]
Hi, 

Sadly I rely on external detection tools, listed on package.json, you should go to them directly.

**Comment by fun7om** [comment]
on that matter:
the auto detection language doesnt work very good on Hebrew. 90% its fails.
since i mostly upload subtitles in my own language,  i wish it had the "LOCK" - same for translator field.
so it will "save between sessions".

**Comment by vankasteelj** [comment]
> 
> 
> on that matter:
> the auto detection language doesnt work very good on Hebrew. 90% its fails.
> since i mostly upload subtitles in my own language, i wish it had the "LOCK" - same for translator field.
> so it will "save between sessions".

that I should be able to do
