### ISSUE TITLE
Wrong video file when opening a subtitle file

### ISSUE THREAD

**Issue by tbertels** [vankasteelj/opensubtitles-uploader#58]
To reproduce:
1. Open a subtitle for a series where every episode has the same name expect for the season and episode numbers (for example "Series Name S01E02.srt")

Result:
"Series Name S01E01.mp4" gets recognized as the video file

Expected result:
"Series Name S01E02.mp4" gets recognized as the video file

![osu](https://user-images.githubusercontent.com/3265870/61351455-0d52ad80-a86b-11e9-8ef7-89cda04647c6.png)

**Comment by vankasteelj** [comment]
Mmh. That shouldn't happen. I'll take a look when I have some time, thank you!

**Comment by R-cloud-pixel** [comment]
Not secure

**Comment by R-cloud-pixel** [comment]
I have a Media player Classic Home cinema installed on my desktop it does not function.

**Comment by R-cloud-pixel** [comment]
Wrong video file when opening a subtitle

**Comment by R-cloud-pixel** [comment]
Wrong video file when opening a subtitle file #67

**Comment by kamazeres2** [comment]
Спасибо

**Comment by R-cloud-pixel** [comment]
I can not read that.
