### ISSUE TITLE
add uk localization

### ISSUE THREAD

**Issue by AucT** [vankasteelj/opensubtitles-uploader#59]
Hi! Nice tool.
I'm not sure if transifex is dead or not, I've requested creating uk locale.

If it is dead here
 uk (Ukrainian) language file

[uk.json.txt](https://github.com/vankasteelj/opensubtitles-uploader/files/3476155/uk.json.txt)

**Comment by vankasteelj** [comment]
Hi, I've just approved your request on Transifex, I'd rather have it there so it's centralized please :) Thanks!

**Comment by vankasteelj** [comment]
Hi, is there any way to reduce the length of those 4 strings? The app doesn't like strings that long, and I havent figured out how to keep the layout with longer strings. 
![nw_2019-08-08_13-51-42](https://user-images.githubusercontent.com/12599850/62701147-e0b23180-b9e3-11e9-8785-0c6743c69129.png)

**Comment by vankasteelj** [comment]
![nw_2019-08-08_14-13-11](https://user-images.githubusercontent.com/12599850/62702309-
ac8c4000-b9e6-11e9-979d-3a08aa2a8651.png)

One last string too long

**Comment by AucT** [comment]
I think you should make checkmark on the left
[checkmark] [icon] [text]

I tried to do so, but your styles are weird with absolute positioning. 
It will improve other translation because now if you place text that has less characters checkmark will be floating.

**Comment by AucT** [comment]
If it's not possible leave english. That one can't be made smaller.
