### ISSUE TITLE
Show imdb title without hovering the 'i' icon

### ISSUE THREAD

**Issue by vankasteelj** [vankasteelj/opensubtitles-uploader#60]
From osforums:

>The problem is that now users only see an IMDb ID and that big image in the background. The actual title is only displayed when hovering the mouse over that "i" icon. Why not have the title display somewhere, without active user interference?
Mind you, with a little bit smart file name, the OS Uploader got it right in -I estimate- 99,9% of the cases. But that's exactly why users do not check and hover that "i" and errors are kind of unnoticed. One small line of text somewhere could probably minimize that.

**Comment by fun7om** [comment]
i experienced this problem about 5 times, with different TV shows,
where i uploaded lets say: S01E02
and it got recognized as S01E03, or it didnt recognized episode, so it gave it the general IMDB series.
but i didnt notice that.
of course they both had the same background pic.
