### ISSUE TITLE
Disable Autosearch IMDB

### ISSUE THREAD

**Issue by G3NSVRV** [vankasteelj/opensubtitles-uploader#63]
Please add the ability to configure (toggle) if we wanna autosearch or not based on the file hash on IMDB. Most of the time I upload the wrong movie IMDB number because is too slow to load the screen; 

# (bug)
I load a subtitle with the video, then I paste and press enter the new IMDB number and loads the movie that I want, then the UI loads the "search that he thinks" and change it again the IMDB for the automatic search.

**Comment by vankasteelj** [comment]
Could maybe be done in "settings" to avoid 'newbies' disabling it. I'll try to think about it

**Comment by vankasteelj** [comment]
okay I see, you can enter the imdb but it still will overwrite it with the background search one.
