### ISSUE TITLE
Add link to "subtitle already present in the database"

### ISSUE THREAD

**Issue by vankasteelj** [vankasteelj/opensubtitles-uploader#67]
Requested by scooby007:

>>>When submitting a hash for a subtitle that already has it, it says: "Subtitle already present in the database, the hash too."
Would it be possible for the program to give you a link to that subtitle? Trivial, but would be nice, if possible.
I did that today for a subtitle, but couldn't see any hashes on it, I'm guessing that part is a site cache issue and will show in 24 hours.

**Comment by R-cloud-pixel** [comment]
I already have deleted that file.
