### ISSUE TITLE
Allow to setup primary language

### ISSUE THREAD

**Issue by JimmyS83** [vankasteelj/opensubtitles-uploader#74]
My language is always unrecongnized. When uploadin multiple subtitles, language settins are always reseted. Option to choose one language as default woudl be appretiated.

On the same note, imdb ID is also always reseted after upload, when you uploading TVshow, its also kinda irritating :)

**Comment by fun7om** [comment]
Dont you have the "Magic Lock" ?

[https://i.ibb.co/LRYyhS8/Screenshot-2020-11-12-235055.jpg](url)
![Screenshot 2020-11-12 235055](https://user-images.githubusercontent.com/41475045/99000793-81c25d00-2542-11eb-9615-4fa7b61698a1.jpg)

**Comment by JimmyS83** [comment]
Ah, I was totally not aware of this. Thank you!  Anyway, I would leave this open, in regards that magic lock would be great also for imdbid in tvshow usecase?

**Comment by vankasteelj** [comment]
Glad you got helped, as for locking the imdbid, I'm gonna refer to #14 instead
