### ISSUE TITLE
Error while uploading - debug mode

### ISSUE THREAD

**Issue by opensubtitles** [vankasteelj/opensubtitles-uploader#76]
Hi,

it is possible to turn on some debug mode ? I need to see what is sent and received to server (http headers + body)

Tha nks

**Comment by vankasteelj** [comment]
That will require manual modifications, but yes: 

change `node_modules/opensubtitles-api/lib/opensubtitles.js`, line 35: 

original:
```js
if (err) return reject(this.handleError(err))
```
becomes >>> 
```js
if (err) return reject({error:err})
```

Then launch the app again, press F12 or CTRL+D, and head to the "console" tab of the chrome debugger (on V2.5)

**Comment by vankasteelj** [comment]
This is what the error should look like after modification:
![opensubtitles-uploader_tv7lqWe9YJ](https://user-images.githubusercontent.com/12599850/103014696-7ef25900-453f-11eb-9917-24aa596971cb.png)

**Comment by opensubtitles** [comment]
thanks!

**Comment by opensubtitles** [comment]
thanks for it, I modified source code, run app again on OSX, trying to upload, I can not see any Network activity and in debug window I got:

![image](https://user-images.githubusercontent.com/23124417/104606593-37fc0d00-5680-11eb-8b79-15671c13fe4b.png)
