### ISSUE TITLE
Can't upload anymore in Windows

### ISSUE THREAD

**Issue by Converted007** [vankasteelj/opensubtitles-uploader#78]
It doesn't work anymore in windows. You get a "something is wrong" popup error message. And that's it.

Can it please be updated again?
Thanks

**Comment by pedrofusc** [comment]
it not working herehere's not working either

**Comment by vankasteelj** [comment]
Something is off with the API, I'll have to make more tests. See https://github.com/vankasteelj/opensubtitles-uploader/issues/76

**Comment by vankasteelj** [comment]
It seems to have resolved itself, let me know if it hasnt
