### ISSUE TITLE
long imdb id

### ISSUE THREAD

**Issue by AucT** [vankasteelj/opensubtitles-uploader#80]
ALthough I can upload subtitle with manually set long imdb id but that error showing is a bit annoying.
Try to set id to tt10322300 or smth with 8 digits and you get notifications about error id

**Comment by vankasteelj** [comment]
I'll have to check that, thanks

**Comment by vankasteelj** [comment]
I've reported the issue here: https://forum.opensubtitles.org/viewtopic.php?f=8&t=17478
