### ISSUE TITLE
OpenSubtitles upload page fails

### ISSUE THREAD

**Issue by superbonaci** [vankasteelj/opensubtitles-uploader#87]
I get this message when trying to [upload valid subtitles](https://www.opensubtitles.org/en/upload):

![](https://static.opensubtitles.org/gfx/css/error_sm.gif) Unsupported subtitle format for CD 1. Only srt, sub, smi, txt and ssa formats are supported B

**Comment by fun7om** [comment]
you should go to https://forum.opensubtitles.org/

**Comment by superbonaci** [comment]
@fun7om try going there yourself

**Comment by fun7om** [comment]
lol N1.
 yea its down. probably will be back tomorrow.

here you wont get any help for the site.
only the Uploader.  

make sure the file you are trying to upload is "clean".
no ads. no site links. no spam.

**Comment by superbonaci** [comment]
LOL you were totally right. Found out that the subtitles file had ads about the site itself:
````
470
01:46:53,541 --> 01:49:12,311
Advertise your product or brand here
contact www.OpenSubtitles.org today
````
just removing them worked instantly!

![](https://i.imgur.com/6EFYBRU.png)

**Comment by superbonaci** [comment]
Duplicate of bug **https://github.com/vankasteelj/opensubtitles-uploader/issues/87**

**Comment by superbonaci** [comment]
Not a program issue. The website scans the subtitle file before accepting it.

**Comment by danielb2** [comment]
getting this error too, but zero indication of what's wrong. not seeing any spam so I don't know what's going on. Was going to share my efforts with everyone, but oh well?

note: i did check for spam but didn't see any. attached is the srt file (renamed to txt since GH won't accept otherwise)

[Beavis.and.Butt-Head.Do.the.Universe (2022).vi.txt](https://github.com/user-attachments/files/19560052/Beavis.and.Butt-Head.Do.the.Universe.2022.vi.txt)

**Comment by fun7om** [comment]
Hello, try remove the YTS thing. That will be 1st and 2nd lines.  Try look for more.
Anyway - you wont get support here for rejected subs - because the problem is Opensubtitles.org and not the machanics of the UPLOADER. Go to the forum .
Goodluck.

**Comment by danielb2** [comment]
that did it. thanks! for some reason I totally glossed over that. For anyone else reading, and who runs into a similar issue, one line simply said `YTS.MX` which I didn't spot as a URL.  A search for `\w\.\w` should catch these.
