### ISSUE TITLE
Please release and update

### ISSUE THREAD

**Issue by opensubtitles** [vankasteelj/opensubtitles-uploader#89]
As users point out - we have been hacked and forced to change the password verification, we are not using md5 (which I think you sending in order to a bit more safe...). This ticket is similar as https://github.com/vankasteelj/opensubtitles-uploader/issues/88

please read about what happened here
https://forum.opensubtitles.org/viewtopic.php?f=1&t=17685&p=46818#p46818

now only way is to say username and password, should be small change.

**Comment by vankasteelj** [comment]
Update in progress
