### ISSUE TITLE
Subtitle already in DB link language attribute

### ISSUE THREAD

**Issue by XxNoobz4LifeXx** [vankasteelj/opensubtitles-uploader#93]
New feature "Subtitle already in DB" looks very useful.

Would it be possible to change the language attribute (for the opensubtitles.org link) from default "fr" into what ever user has set as OS-U display language?

**Comment by vankasteelj** [comment]
You're right, I've hardcoded /fr/ in the url. Would you have the url it sends you to for me to check some things? The API doesn't send back where the subtitle is available, so I dont have a proper url and have to build it using only the "subtitle ID" number, idk what are the langcodes used by Opensubtitles for those urls, but maybe I can bypass it or use a 2-lang ID iso format, my fear is that it wouldnt work for all languages, so i'd like to test before "simply" hardcoding the user language into an url

**Comment by XxNoobz4LifeXx** [comment]
Did test this on Show Peacemaker S01E04 as did notice it had Finnish subs I could test. 
URL that opens:
https://www.opensubtitles.org/fr/subtitles/8950971/peacemaker-the-choad-less-traveled-fi
URL that should (if possible) open:
https://www.opensubtitles.org/fi/subtitles/8950971/peacemaker-the-choad-less-traveled-fi

Did look that inside DevTools the link looks like:
('https://www.opensubtitles.org/fr/subtitles/8950971')

In opensubtitles.org, when I click Site Language link and hover mouse over the flags it shows the language attribute and they seems basic Alpha-2 codes.

**Comment by vankasteelj** [comment]
Okay great, thanks. Looks like omitting the language does work. Would this url be more like what you expect: https://www.opensubtitles.org/subtitles/8950971 ? It seems to opens in english by default for me, wheter I'm logged in or not on opensubtitles. Adding manual language to the URL might break some things, as I said before, as idk for some languages (there are variants in chinese for example, and portugese from brazil also is not always represented by the same letters everywhere)

**Comment by XxNoobz4LifeXx** [comment]
Yes, that does seem to be the most safest option.
