### ISSUE TITLE
Some video fields are empty

### ISSUE THREAD

**Issue by fun7om** [vankasteelj/opensubtitles-uploader#94]
after update to 2.6.0 some auto detect fields are not recognized.

screenshot
https://ibb.co/BNbxJ39

console

```
Logged in! (as fun7om - ID:5673380)
app.js:40 Application ready: 3563.80615234375 ms
keyboard.js:19 Opening devtools
files.js:29 Detecting quality...
interface.js:41 Adding new video!
files.js:258 MediaInfo detection failed, continuing... Error: Command failed: "C:\תוכנות\upload subtitles\opensubtitles-uploader-2.6.0-win32-portable\node_modules\mediainfo-wrapper\lib\win32\mediainfo.exe" --Output=XML --Full "C:/תוכנות/emule/Marvel's.The.Punisher.SEASON.02.S02.COMPLETE.720p.10bit.WEBRip.2CH.x265.HEVC-PSA/Marvel's.The.Punisher.S02E01.Roadhouse.Blues.720p.10bit.WEBRip.2CH.x265.HEVC-PSA.mkv"
The system cannot find the path specified.

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
(anonymous) @ files.js:258
processTicksAndRejections @ node:internal/process/task_queues:94
misc.js:94 Looking online for a fanart...
interface.js:137 Matching subtitle detected
interface.js:236 Adding new subtitle!
files.js:121 Detecting if subtitle was machine translated...
files.js:143 Detecting if subtitle contains sounds description...
files.js:159 Detecting if subtitle is foreign only...
interface.js:567 Loading image https://image.tmdb.org/t/p/w1280/2yfmJudf695JBUJRW7QJjVN1rg5.jpg

```

**Comment by vankasteelj** [comment]
Hi, thanks. Can you manually check that "mediainfo.exe" is present inside your `C:\תוכנות\upload subtitles\opensubtitles-uploader-2.6.0-win32-portable\node_modules\mediainfo-wrapper\lib\win32` directory? 

It looks like it's non there, but I'm also wondering if the non-standard characters in your local path (is that Hebrew btw?) might have something to do with it.

**Comment by XxNoobz4LifeXx** [comment]
I don't think there is win32 folder inside ...mediainfo-wrapper/lib at all.
Did test by using executable to install it into:
- C:\Program Files (another bug here, drag and drop doesn't work)
- C:\Program Files (x86)
and downloaded the opensubtitles-uploader-2.6.0-win32-portable.zip
file, then looked inside with Windows file explorer and latest 7zip = nothing in under mediainfo-wrapper/lib folder.

![OpenSubtitle-Uploader_260_empty_media-wrapper](https://user-images.githubusercontent.com/92278675/150682196-a76afb1d-f362-4ebf-a124-ac6a3aa5fe0c.png)
There are under ...mediainfo-wrapper/
- lib (empty folder)
- index.js
- package,json

**Comment by fun7om** [comment]
> Hi, thanks. Can you manually check that "mediainfo.exe" is present inside your `C:\תוכנות\upload subtitles\opensubtitles-uploader-2.6.0-win32-portable\node_modules\mediainfo-wrapper\lib\win32` directory?
> 
> It looks like it's non there, but I'm also wondering if the non-standard characters in your local path (is that Hebrew btw?) might have something to do with it.

YEP. like XxNoobz4LifeXx said
.../lib/   is empty, someone  forgot about it lol.

btw it's exist in 2.5.0

and you are correct sir, the non-Latin chars are Hebrew, so HELLO from Israel !

**Comment by NunoVilhenaSantos** [comment]
Hi,

The same here

It's the install version 2.6.0

<a href="https://ibb.co/MRwGB35"><img src="https://i.ibb.co/THjbWFq/2022-02-06-16-16-07.png" alt="2022-02-06-16-16-07" border="0"></a>

**Comment by JIMISK21** [comment]
I can confirm the fix mentioned from @fun7om works perfect!

Just download  v2.5.0 copy the subfolders "lib" and "node_modules"  from path ( ...\opensubtitles-uploader-2.6.0-win32-portable\node_modules\mediainfo-wrapper)

and paste the folders to the same path in  v2.6.0
