### ISSUE TITLE
Many Issues language detection

### ISSUE THREAD

**Issue by hajimekun** [vankasteelj/opensubtitles-uploader#97]
In Advanced Subtitle Station format:
The app fail to detect the Spanish (Spain) language
Fails to recognize the differece between Portuguese and Portuguese BR (same as 3 types of chienese)
Sometimes recognize English as Icelandic

**Comment by vankasteelj** [comment]
Could you provide the files that are misidentified? It's not AI-powered so it has to rely on manual tweaks and predictions using a dictionnary, it's not perfect (nor will it ever be), but it might be tweaked better

**Comment by tbertels** [comment]
[Not detected (English).zip](https://github.com/vankasteelj/opensubtitles-uploader/files/8944529/Not.detected.English.zip)
[Detected as German instead of English.zip](https://github.com/vankasteelj/opensubtitles-uploader/files/8944530/Detected.as.German.instead.of.English.zip)

**Comment by vankasteelj** [comment]
@tbertels your examples are fixed in the sources

**Comment by vankasteelj** [comment]
@hajimekun without your files I cannot do anything more.

**Comment by tbertels** [comment]
I've just had a new "Files.detectSubLang() error: not conclusive enough
(anonymous) @ files.js:112" error, here's the subtitle:
[Not detected (English) 2.zip](https://github.com/vankasteelj/opensubtitles-uploader/files/11453018/Not.detected.English.2.zip)

**Comment by vankasteelj** [comment]
The probability of "english" was below the 25% treshold. For that specific file, it's 24.16% detected as english. FYI: Only 72 sentences were detected as "english" in your file, but the algorithm also thinks 40 sentences are in "scots". There is nothing more I can do at that point. I can't go lower on the treshold or it will cause issue and risk misinterpreting subtitles lang. The point is : be sure or don't auto-fill. Not "guess hoping it's right"
